name: Run Build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Build PWA
        run: npm run build