name: Client

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopend

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./client
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
        working-directory: ${{env.working-directory}}
      - name: Run Lint
        run: npm run lint
        working-directory: ${{env.working-directory}}
      - name: Build PWA
        run: npm run build
        working-directory: ${{env.working-directory}}
      - name: Run Tests
        run: npm run test
        working-directory: ${{env.working-directory}}
  preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    env:
      working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      - name: 'Install Dependencies and build'
        run: npm ci && npm run build
        working-directory: ${{env.working-directory}}
      - name: Deploy Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_POOLSCORE_1973 }}'
          projectId: poolscore-1973
