name: Cloud Functions

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopend

jobs:
  functions_test:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./functions
      GOOGLE_APPLICATION_CREDENTIALS: /opt/gcp_key.json
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
        working-directory: ${{env.working-directory}}
      # Emulator requires login. See: https://github.com/firebase/firebase-tools/issues/5510
      - name: Export service account credentials to file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_POOLSCORE_1973 }}' > '${{ env.GOOGLE_APPLICATION_CREDENTIALS }}'
      - name: Run Lint
        run: npm run lint
        working-directory: ${{env.working-directory}}
      - name: Build
        run: npm run build
        working-directory: ${{env.working-directory}}
      - name: Run Tests
        run: npm run test
        working-directory: ${{env.working-directory}}