name: Run Lint

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopend
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint