name: Run Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test